Hava-durumu/Models/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hava_durumu.Models
{
    public class AppIndexViewModel
    {
        //public WeatherSaveModel SaveWeather { get; set; }
        //public string JsonString { get; set; }
        public Search Search { get; set; }
        public CommentSaveModel SaveComment { get; set; }
        public IEnumerable<Comment> Comments { get; set; }

    }
    public class WeatherSaveModel
    {
        public double Lat { get; set; }
        public double Lon { get; set; }
        public string Icon { get; set; }
        public double Temp { get; set; }
        public double TempMin { get; set; }
        public double TempMax { get; set; }
        public double Humidity { get; set; }
        public string Main { get; set; }
        public string Description { get; set; }
        public double Winds { get; set; }
        public double Clouds { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public int CityID { get; set; }
        public int Code { get; set; }
        public int WeatherInfoId { get; set; }
        public string Language { get; set; }
    }

    public class WeatherAjax
    {
        public string Data { get; set; }
    }

    public class CommentAjax
    {
        public string Data { get; set; }
    }
    
    public class CommentSaveModel
    {
        public string WriterName { get; set; }
        public string Content { get; set; }
        public string City { get; set; }
        public string Language { get; set; }
        public int WeatherInfoID { get; set; }
    }

    public class Search
    {
        public string City { get; set; }
        public double? Lat { get; set; }
        public double? Lon { get; set; }
        public double OldLat { get; set; }
        public double OldLon { get; set; }
    }

    public class SearchAjax
    {
        public string Data { get; set; }
    }
}

Hava-durumu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Threading;
using System.Globalization;
using Hava_durumu.Models;
using System.Net;

namespace Hava_durumu.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string language)
        {
            SetCulture(language);

            //var db = new CommentDBContext();
            //var user = new User();
            //user.FirstName = "Fawzy";
            //user.LastName = "Abderrahman";
            //user.Name = "Fawzy Abderrahman";
            //user.Email = "fawzy@example.com";
            //db.Users.Add(user);

            //var comment = new Comment();
            //comment.Date = DateTime.Now;
            //comment.Title = "Test1";
            //comment.WritingUser = user;
            //db.Comments.Add(comment);
            //db.SaveChanges();
            //db.Dispose();

            //var appid = "98b67b8f5333c2991374b3e33cbee535";
            //var lat = 63.22;
            //var lon = 30.27;
            //var url = string.Format("http://api.openweathermap.org/data/2.5/weather?units=metric&lat={0}&lon={1}&appid={2}", lat, lon, appid);

            //using (WebClient client = new WebClient())
            //{
            //    string json = client.DownloadString(url);
            //    JObject ob = new JObject(json);
            //    return Content(json);
            //}

            ViewBag.Lang = language;

            return View(new Search());
        }

        [HttpPost]
        public ActionResult Index(/*Search data*/ string SearchAjax, string language)
        {
            SetCulture(language);

            var data = JsonConvert.DeserializeObject<Search>(SearchAjax);
            Coordinates coord = null;
            //var data = AppModel.Search;
            if (data.City != null && data.City.ToLower() != Hava_durumu.Languages.lang.WeatherInfosCity.ToLower())
            {
                coord = GetCityCoord(data.City);
            }
            if (coord == null)
            {
                coord = new Coordinates();
                if (data.Lat != null && data.Lat != 0.0 && data.Lon != null && data.Lon != 0.0)
                {
                    coord.Lat = (double)data.Lat;
                    coord.Lon = (double)data.Lon;
                }
                else
                {
                    coord.Lat = (double)data.OldLat;
                    coord.Lon = (double)data.OldLon;
                }
            }
            
            ViewBag.Lang = language;
            ViewBag.Lat = coord.Lat;
            ViewBag.Lon = coord.Lon;
            return View(new Search());
        }

        public ActionResult About(string language)
        {
            SetCulture(language);

            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact(string language)
        {
            SetCulture(language);

            ViewBag.Message = "Your contact page.";

            return View();
        }

        public void SetCulture(string language)
        {
            if (Thread.CurrentThread.CurrentCulture.Name != language)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);
            }
        }
        public Coordinates GetCityCoord(string cityName)
        {
            //var db = new ApplicationDbContext();
            var city = new City();
            //var city = db.Cities.First(x => x.Name.ToLower().Contains(cityName.ToLower()));
            //if (city != null)
            //{
            //    db.Dispose();
            //    return city.Coord;
            //}
            //else
            //{
            string path = Server.MapPath("~/Data/city-list.json");
            var file = new System.IO.StreamReader(path);
            string line;
            while (!file.EndOfStream)
            {
                line = file.ReadLine();
                //var job = (JObject)JsonConvert.DeserializeObject(line);
                //Console.WriteLine(line);
                //Console.WriteLine("id:{0}", job.Value<int>("id"));
                //Console.WriteLine("name:{0}", job.Value<string>("name"));
                //Console.WriteLine("country:{0}", job.Value<string>("country"));
                //Console.WriteLine("coord: lat:{0} lon:{1}", job.Value<JToken>("coord").Value<double>("lat"), job.Value<JToken>("coord").Value<double>("lon"));
                city = JsonConvert.DeserializeObject<City>(line);
                //Console.WriteLine(line);
                //Console.WriteLine("id:{0}", city.ID);
                //Console.WriteLine("name:{0}", city.Name);
                //Console.WriteLine("country:{0}", city.Country);
                //Console.WriteLine("coord: lat:{0} lon:{1}", city.Coord.Lat, city.Coord.Lon);
                if (TrimSpaceAndLower(city.Name).StartsWith(TrimSpaceAndLower(cityName)))
                {
                    //            db.Cities.Add(city);
                    //            db.SaveChanges();
                    //            db.Dispose();
                    return city.Coord;
                }
                //    }  
            }
            return null;
        }

        public string TrimSpace(string text)
        {
            string[] res = text.Split(' ');
            string result = "";
            foreach(var item in res)
            {
                result += item;
            }
            return result;
        }
        public string TrimSpaceAndLower(string text)
        {
            string[] res = text.Split(' ');
            string result = "";
            foreach (var item in res)
            {
                result += item;
            }
            return result.ToLower();
        }
    }
}

Hava-durumu/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hava_durumu.Models;
using Newtonsoft.Json;

namespace Hava_durumu.Controllers
{
    public class WeatherController : Controller
    {
        // GET: Weather
        [HttpPost]
        public JsonResult Save(WeatherAjax weatherAjax)
        {
            if (ModelState.IsValid)
            {
                var db = new ApplicationDbContext();
                WeatherInfo weatherInfo;
               
                var weather = JsonConvert.DeserializeObject<WeatherSaveModel>(weatherAjax.Data);

                try
                {
                    weatherInfo = db.WeatherInfos.DefaultIfEmpty(null).OrderBy(x => x.Date).Where(x => x.City.Name == weather.Name && x.Language == weather.Language).LastOrDefault(x => (Math.Abs(x.Date.Ticks - DateTime.Now.Ticks)) < 6000000000);
                }
                catch (Exception)
                {
                    weatherInfo = null;
                }
                if (weatherInfo == null)
                {
                    //var city = new City()
                    //{
                    //    ID = weather.CityID,
                    //    Country = weather.Country,
                    //    Name = weather.Name,
                    //    Coord = new Coordinates()
                    //    {
                    //        Lat = weather.Lat,
                    //        Lon = weather.Lon
                    //    }
                    //};
                    var city = GetCity(weather.Name);
                    //var infoWeather = new Weather()
                    //{
                    //    Id = weather.WeatherInfoId,
                    //    Description = weather.Description,
                    //    Icon = weather.Icon,
                    //    Main = weather.Main
                    //};
                    var infoWeather = GetWeather(weather.Main, weather.Icon, weather.Language, weather.Description);

                    var values = new WeatherValues()
                    {
                        Clouds = weather.Clouds,
                        Humidity = weather.Humidity,
                        Temp = weather.Temp,
                        TempMax = weather.TempMax,
                        TempMin = weather.TempMin,
                        Winds = weather.Winds
                    };
                    weatherInfo = new WeatherInfo()
                    {
                        CityID = city.ID,
                        Date = DateTime.Now,
                        WeatherID = infoWeather.Id,
                        Values = values,
                        Code = weather.Code,
                        Language = weather.Language
                    };

                    db.WeatherInfos.Add(weatherInfo);
                    db.SaveChanges();
                    db.Dispose();
                }
                return Json(new { Lat = weather.Lat
                , Lon = weather.Lon
                , City = weather.Name
                , Country = weather.Country });
            }
            return null;
        }

        public City GetCity(string cityName)
        {
            var db = new ApplicationDbContext();
            City city = null;
            try
            {
                city = db.Cities.DefaultIfEmpty(null).FirstOrDefault(x => x.Name.ToLower().StartsWith(cityName.ToLower()));
            }
            catch (Exception)
            {
                city = null;
            }
            if (city != null)
            {
                db.Dispose();
                return city;
            }
            else
            {
                string path = Server.MapPath("~/Data/city-list.json");
                var file = new System.IO.StreamReader(path);
                string line;
                while (!file.EndOfStream)
                {
                    line = file.ReadLine();
                    city = JsonConvert.DeserializeObject<City>(line);
                    if (city.Name.ToLower().StartsWith(cityName.ToLower()))
                    {
                        db.Cities.Add(city);
                        db.SaveChanges();
                        db.Dispose();
                        return city;
                    }
                }
            }
            return null;
        }

        public Weather GetWeather(string main, string icon, string language, string description)
        {
            var db = new ApplicationDbContext();
            Weather weather;
            try
            {
                weather = db.Weathers.DefaultIfEmpty(null).First(x => x.Main == main && x.Icon == icon && x.Language == language);
            }
            catch (Exception)
            {
                weather = null;
            }
            if (weather == null)
            {
                weather = new Weather() { Icon = icon, Main = main, Language = language, Description = description };
                db.Weathers.Add(weather);
                db.SaveChanges();
                db.Dispose();
            }
            return weather;
        }

        public string TrimSpace(string text)
        {
            string[] res = text.Split(' ');
            string result = "";
            foreach (var item in res)
            {
                result += item;
            }
            return result;
        }
        public string TrimSpaceAndLower(string text)
        {
            string[] res = text.Split(' ');
            string result = "";
            foreach (var item in res)
            {
                result += item;
            }
            return result.ToLower();
        }

        //For test purpose
        public class test
        {
            public string Name { get; set; }
            public string LastName { get; set; }
        }
    }
}

Hava-durumu/Views/Home/About.cshtml
@{
    ViewBag.Title = Hava_durumu.Languages.lang.AboutPageTitle;
}
<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4" id="mission">
        <div class="panel panel-default panel-custom">
            <div class="panel-heading">
                <h3 class="panel-title" id="title">@Hava_durumu.Languages.lang.AboutMission</h3>
            </div>
            <div class="panel-body">
                <p>
                    Our mission is to make available the weather forecast to all and 
                    in a simple and an efficient way. No matter who is navigating through
                    our web pages, he/she is awaited to find it pleasant.
                </p> <br />
                <p>
                    We use real-time data provided by <a href="http://www.openweathermap.org" target="_blank">open weather</a>. As
                    it is complex to manipulate weather datas, we make it easy to the user to understand.
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4" id="usage-info">
        <div class="panel panel-default panel-custom">
            <div class="panel-heading">
                <h3 class="panel-title" id="title">@Hava_durumu.Languages.lang.AboutUsageInformation</h3>
            </div>
            <div class="panel-body">
                <p>
                    Having a good use-experience is crucial to any application so here are some tips.
                    This section is made intentionaly for the end-user.
                </p>
                <p>
                    <ul>
                        <li>From the map, choose any location by simply clicking or
                    from the search bar the name of a city.</li>
                        <li>Play with the navigation tab.</li>
                        <li>Change the language from the Languages dropdown in the top menu.</li>
                        <li>Leave a comment to if you have anything you want to share.</li>
                    </ul>
                    Enjoy!
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4" id="support">
        <div class="panel panel-default panel-custom">
            <div class="panel-heading">
                <h3 class="panel-title" id="title">@Hava_durumu.Languages.lang.AboutSupport</h3>
            </div>
            <div class="panel-body">
                <p>
                    To help us improve our service please let us know your comments, requests and ideas.
                    See @Html.ActionLink("contact us", "Contact", "Home")
                </p>
            </div>
        </div>
    </div>
</div>

Hava-durumu/Views/Home/Contact.cshtml
@{
    ViewBag.Title = Hava_durumu.Languages.lang.ContactPageTitle;
}
<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4" id="about-me">
        <div class="panel panel-default panel-custom">
            <div class="panel-heading">
                <h3 class="panel-title" id="title">@Hava_durumu.Languages.lang.ContactAboutAuthor</h3>
            </div>
            <div class="panel-body">
                <p>
                    
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4" id="address">
        <div class="panel panel-default panel-custom">
            <div class="panel-heading">
                <h3 class="panel-title" id="title">@Hava_durumu.Languages.lang.ContactAddress</h3>
            </div>
            <div class="panel-body">
                <p>

                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4" id="leave-message">
        <div class="panel panel-default panel-custom">
            <div class="panel-heading">
                <h3 class="panel-title" id="title">@Hava_durumu.Languages.lang.ContactMessage</h3>
            </div>
            <div class="panel-body">
                <p>
                    
                </p>
            </div>
        </div>
    </div>
</div>


@*<div id="about-me">
    <p>About me</p>
</div>

<div id="leave-message">
    <p>Leave your massage</p>
</div>

<address>
    <strong>Support:</strong>   <a href="mailto:fawzy.abderrahmant9875@gmail.com">author</a><br />
</address>*@

Hava-durumu/Views/Home/Index.cshtml
@model Hava_durumu.Models.Search
@{
    ViewBag.Title = Hava_durumu.Languages.lang.HomePageTitle;
    <div hidden @*style="display:none"*@>
        <input id="lang" value="@ViewBag.Lang" />
        <input id="lat" value="@ViewBag.Lat"/>
        <input id="lon" value="@ViewBag.Lon" />
    </div>
    <script>
        var lat = document.getElementById('lat').getAttribute('value');
        var lon = document.getElementById('lon').getAttribute('value');
        var lang = document.getElementById('lang').getAttribute('value');
    </script>
}

<!--Search area appears in top of the page when the page is sm-->

    @*@using (Html.BeginForm("Index", "Home", new { language = ViewContext.RouteData.Values["language"].ToString() }, FormMethod.Post, new { @class = "form-inline" }))
    {
        @Html.AntiForgeryToken()

        <div class="row fadein" id="search">
            @*<form class="form-inline">
            <div class="form-group col-xs-5">
                <input type="text" name="City" class="form-control col-xs-12" value="@Hava_durumu.Languages.lang.WeatherInfosCity" id="search-bar">
            </div>
            <button class="btn btn-default" id="search-btn">@Hava_durumu.Languages.lang.WeatherInfosSearch</button>
            @*</form>
            @Html.Partial("_IndexSearchPartial")
        </div>
    }*@
@*@{ var m = new Hava_durumu.Models.Search(); }*@
@Html.Partial("_IndexSearchPartial")

@*@using (Html.BeginForm("Index", "Home", new { language = ViewContext.RouteData.Values["language"].ToString() }, FormMethod.Post, new { @class = "form-inline" }))
{
    @Html.AntiForgeryToken()

    <div class="row fadein" id="search">
        <div class="form-group col-xs-5">
            @Html.TextBoxFor(m => m.Search.City, new { @class = "form-control col-xs-12", value = @Hava_durumu.Languages.lang.WeatherInfosCity, id = "new-city-name" })
            @Html.TextBoxFor(m => m.Search.Lon, new { id = "new-city-lon" })
            @Html.TextBoxFor(m => m.Search.Lat, new { id = "new-city-lat" })
            @Html.TextBoxFor(m => m.Search.OldLat, new { id = "old-city-lat" })
            @Html.TextBoxFor(m => m.Search.OldLon, new { id = "old-city-lon" })
        </div>
        <button type="submit" class="btn btn-default" id="search-btn">@Hava_durumu.Languages.lang.WeatherInfosSearch</button>
    </div>
}*@

@*<button id="test">click</button>*@
        

<!--Displaying the map and info in a single row-->
<div class="row">
    <div class="col-md-8 divide-custom">
        <div class="row">
            <div class="col-sm-12 col-md-11" id="map">
                <!--Displaying a map via google maps api-->
                <div id="map-canvas">
                    
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-4" id="info">
        <div class="fadeout" id="search">
            <form class="form-inline">
                <div class="form-group">
                    <input type="text" class="form-control search-trigger-box" value="@Hava_durumu.Languages.lang.WeatherInfosCity" id="search-bar">
                </div>
                <div class="form-group">
                    @*<button class="btn btn-default" id="search-btn">@Hava_durumu.Languages.lang.WeatherInfosSearch</button>*@
                    <a class="btn btn-default search-trigger" id="search-btn" href="#">@Hava_durumu.Languages.lang.WeatherInfosSearch</a>
                </div>
            </form>
        </div>
        <ul class="nav nav-tabs" role="tablist" id="tab">
            <li role="presentation" class="active"><a href="#current-weather" aria-controls="current-weather" role="tab" data-toggle="tab">@Hava_durumu.Languages.lang.WeatherInfosCurrent</a></li>
            <li role="presentation"><a href="#hourly" aria-controls="hourly" role="tab" data-toggle="tab">@Hava_durumu.Languages.lang.WeatherInfosHourly</a></li>
            <li role="presentation"><a href="#daily" aria-controls="daily" role="tab" data-toggle="tab">@Hava_durumu.Languages.lang.WeatherInfosDaily</a></li>
            <li role="presentation"><a href="#chart" aria-controls="chart" role="tab" data-toggle="tab">@Hava_durumu.Languages.lang.WeatherInfosChart</a></li>
        </ul>
        <div class="tab-content" id="weather-infos">
            <!--Displaying current weather-->
            <div class="tab-pane active" role="tabpanel" id="current-weather">
                <h3 id="current-weather-city-country"></h3>
                <div>
                    <img id="current-weather-image" />
                    <span id="current-weather-temp"></span> 
                </div>
                
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <td>@Hava_durumu.Languages.lang.WeatherInfosHumidity</td>
                            <td id="current-weather-humidity"></td>
                        </tr>
                        <tr>
                            <td>@Hava_durumu.Languages.lang.WeatherInfosMain</td>
                            <td id="current-weather-main"></td>
                        </tr>
                        <tr>
                            <td>@Hava_durumu.Languages.lang.WeatherInfosDescription</td>
                            <td id="current-weather-description"></td>
                        </tr>
                        <tr>
                            <td>@Hava_durumu.Languages.lang.WeatherInfosWind</td>
                            <td id="current-weather-wind"></td>
                        </tr>
                        <tr>
                            <td>@Hava_durumu.Languages.lang.WeatherInfosClouds</td>
                            <td id="current-weather-clouds"></td>
                        </tr>
                    </tbody>
                </table>                
            </div>
            <!--Hourly forecast-->
            <div class="tab-pane" role="tabpanel" id="hourly">
                Hourly forecast
            </div>
            <!--Displaying daily weather changes-->
            <div class="tab-pane" role="tabpanel" id="daily">
                Daily forecast
            </div>
            <!--Displaying weather chart-->
            <div class="tab-pane" role="tabpanel" id="chart">
                Chart
            </div>
            @*@Html.ActionLink("Save", "Save", "Weather", new { language = ViewContext.RouteData.Values["language"].ToString() }, new { @id = "save-weather-url" })*@
        </div>
    </div>
</div>

<!--Displaying comments and clothing sections in a single row-->
<div class="row divide">
    <div class="col-md-8 divide-custom">
        <div class="row">
            <div class="col-sm-12 col-md-11" id="comments">
                <h3>@Hava_durumu.Languages.lang.Comments</h3>
                <hr />
                <div id="comments-area">
                    <!--One comment-->
                    <div class="comment" id="comment-1">
                        <p class="main-comment">Comment 1</p>
                        <p class="additional-comment-info">by user1, 12-11-2016</p>
                    </div>
                    @*<!--One comment-->
                    <div class="comment" id="comment-2">
                        <p class="main-comment">Comment 2</p>
                        <p class="additional-comment-info">by user2, 12-11-2016</p>
                    </div>
                    <!--One comment-->
                    <div class="comment" id="comment-3">
                        <p class="main-comment">Comment 3</p>
                        <p class="additional-comment-info">by user3, 12-11-2016</p>
                    </div>
                    <!--One comment-->
                    <div class="comment" id="comment-4">
                        <p class="main-comment">Comment 4</p>
                        <p class="additional-comment-info">by user4, 12-11-2016</p>
                    </div>*@
                    <div id="user-comment">
                        @if (Request.IsAuthenticated)
                        {
                            <form class="form-horizontal" id="leave-comment">
                                <div class="form-group">
                                    <textarea class="form-control" cols="120" rows="2"></textarea>
                                </div>
                                <div class="form-group col-sm-offset-5">
                                    <button type="submit" class="btn btn-default">@Hava_durumu.Languages.lang.CommentsLeaveComment</button>
                                </div>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4" id="clothing">
        <h3>@Hava_durumu.Languages.lang.ClothingTip</h3>
        <hr />
        <div id="clothing-tip">
            @*<p>
                For a clear sky and freezing weather there is no need
                to an umbrella, instead wear lite warm cloths
                without overloading yourself.
            </p>*@
        </div>
    </div>
</div>

@section scripts {
    <script src="../../Scripts/index.js" id="map-script"></script>
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCzrJ1yYaHPzKLylNe7ecHCvoSd8EJvQYs&callback=initMap" async defer></script>
}